---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/meseconslab.minetest.ch
  tasks:
    - name: Checkout git
      ansible.builtin.git:
        repo: https://github.com/mesecons-lab/meseconslab.minetest.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: main

    - name: Template minetest config
      template:
        src: "minetest.conf"
        dest: "{{compose_directory}}/minetest.conf"

    - name: Template matterbridge config
      template:
        src: "matterbridge.toml"
        dest: "{{compose_directory}}/matterbridge.toml"

    - name: Create and start services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes
